[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production]
variables = { 
  NODE_ENV = "production",
  PORT = "3001",
  GEMINI_API_KEY = "${{ secrets.GEMINI_API_KEY }}",
  CORS_ORIGINS = "https://devlab-frontend.vercel.app,https://devlab-frontend-git-main.vercel.app"
}

[environments.staging]
variables = { 
  NODE_ENV = "staging",
  PORT = "3001",
  GEMINI_API_KEY = "${{ secrets.GEMINI_API_KEY }}",
  CORS_ORIGINS = "https://devlab-frontend-staging.vercel.app"
}




