apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlab-backend
  namespace: devlab
  labels:
    app: devlab-backend
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devlab-backend
  template:
    metadata:
      labels:
        app: devlab-backend
        version: v1.0.0
    spec:
      containers:
      - name: backend
        image: devlab/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: devlab-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: devlab-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: devlab-secrets
              key: jwt-secret
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: devlab-secrets
              key: gemini-api-key
        - name: SANDBOX_API_URL
          valueFrom:
            secretKeyRef:
              name: devlab-secrets
              key: sandbox-api-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        fsGroup: 1001
