apiVersion: v1
kind: Secret
metadata:
  name: devlab-secrets
  namespace: devlab
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: cG9zdGdyZXNxbDovL2RldmxhYjpkZXZsYWJfcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9kZXZsYWI=
  redis-url: cmVkaXM6Ly9yZWRpczozNjM5
  jwt-secret: ZGV2LXNlY3JldC1rZXk=
  gemini-api-key: ZGV2LWdlbWluaS1rZXk=
  sandbox-api-url: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  rabbitmq-url: YW1xcDovL2RldmxhYjpkZXZsYWJfcGFzc3dvcmRAbG9jYWxob3N0OjU2NzI=
